# Generated by Django 4.1.5 on 2023-01-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Food name')),
                ('cal', models.PositiveIntegerField(help_text='Kcal', null=True, verbose_name='Food calories')),
            ],
        ),
    ]
