# Generated by Django 4.1.5 on 2023-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal', models.PositiveIntegerField(help_text='Kcal', null=True, verbose_name='Food calories')),
            ],
        ),
        migrations.RemoveField(
            model_name='foods',
            name='cal',
        ),
    ]
