# Generated by Django 4.1.5 on 2023-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_cal_remove_foods_cal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cal',
        ),
        migrations.AddField(
            model_name='foods',
            name='cal',
            field=models.PositiveIntegerField(help_text='Kcal', null=True, verbose_name='Food calories'),
        ),
    ]
