# Generated by Django 4.1.5 on 2023-01-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_delete_cal_foods_cal'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal', models.PositiveIntegerField(null=True, verbose_name='foods.cal')),
            ],
        ),
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Food name'),
        ),
    ]
