# Generated by Django 4.1.5 on 2023-01-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_foodcal_alter_foods_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcal',
            name='cal',
        ),
    ]
