# Generated by Django 4.1.5 on 2023-01-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_foodcal_cal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foodcal',
        ),
    ]
