# Generated by Django 4.1.5 on 2023-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_delete_foodcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='a',
            field=models.CharField(max_length=200, null=True, verbose_name='foods.cal'),
        ),
    ]
