# Generated by Django 4.1.5 on 2023-01-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_foods_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='a',
        ),
    ]
