# Generated by Django 4.1.5 on 2023-01-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_remove_foods_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Food name'),
        ),
    ]
