# Generated by Django 4.1.5 on 2023-01-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Dessert name')),
                ('cal', models.PositiveIntegerField(help_text='Kcal', null=True, verbose_name='Dessert calories')),
            ],
        ),
        migrations.CreateModel(
            name='nuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Nuts name')),
                ('cal', models.PositiveIntegerField(help_text='Kcal', null=True, verbose_name='Nuts calories')),
            ],
        ),
    ]
