# Generated by Django 4.1.5 on 2023-01-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_dessert_nuts'),
    ]

    operations = [
        migrations.CreateModel(
            name='snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Snacks name')),
                ('cal', models.PositiveIntegerField(help_text='Kcal', null=True, verbose_name='Snacks calories')),
            ],
        ),
    ]
