# Generated by Django 4.1.5 on 2023-01-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_snacks'),
        ('program', '0018_remove_program_nuts_program_snacks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nuts',
        ),
    ]
