# Generated by Django 4.1.5 on 2023-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='meal',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner')], max_length=200, null=True),
        ),
    ]
