# Generated by Django 4.1.5 on 2023-01-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_program_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='foods',
        ),
    ]
