# Generated by Django 4.1.5 on 2023-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_program_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='foodcal',
            field=models.PositiveIntegerField(null=True, verbose_name='foods.foodcal'),
        ),
    ]
