# Generated by Django 4.1.5 on 2023-01-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_remove_program_foodcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='a',
            field=models.CharField(max_length=200, null=True, verbose_name='foodss.cal'),
        ),
    ]
