# Generated by Django 4.1.5 on 2023-01-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_alter_program_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='note',
            field=models.TextField(max_length=300, null=True, verbose_name='Note'),
        ),
    ]
