# Generated by Django 4.1.5 on 2023-01-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_program_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='a',
        ),
        migrations.AlterField(
            model_name='program',
            name='note',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Note'),
        ),
    ]
