# Generated by Django 4.1.5 on 2023-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_remove_program_a_alter_program_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='a',
            field=models.PositiveIntegerField(null=True, verbose_name='foods.cal'),
        ),
    ]
