# Generated by Django 4.1.5 on 2023-01-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_drink'),
        ('program', '0015_program_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='a',
        ),
        migrations.AddField(
            model_name='program',
            name='drinks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.drink'),
        ),
    ]
