# Generated by Django 4.1.5 on 2023-01-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_dessert_nuts'),
        ('program', '0016_remove_program_a_program_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.dessert'),
        ),
        migrations.AddField(
            model_name='program',
            name='nuts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.nuts'),
        ),
        migrations.AlterField(
            model_name='program',
            name='drinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.drink'),
        ),
    ]
