# Generated by Django 4.1.5 on 2023-01-11 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_snacks'),
        ('program', '0017_program_dessert_program_nuts_alter_program_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='nuts',
        ),
        migrations.AddField(
            model_name='program',
            name='snacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.snacks'),
        ),
    ]
