# Generated by Django 4.1.5 on 2023-01-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_remove_program_nuts_program_snacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='a',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
