# Generated by Django 4.1.5 on 2023-01-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_program_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='a',
        ),
        migrations.RemoveField(
            model_name='program',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='program',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='program',
            name='snacks',
        ),
    ]
