# Generated by Django 4.1.5 on 2023-01-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_delete_nuts'),
        ('program', '0020_remove_program_a_remove_program_dessert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.dessert'),
        ),
        migrations.AddField(
            model_name='program',
            name='drinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.drink'),
        ),
        migrations.AddField(
            model_name='program',
            name='snacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.snacks'),
        ),
    ]
