# Generated by Django 4.1.5 on 2023-01-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0022_program_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='cal',
        ),
    ]
