# Generated by Django 4.1.5 on 2023-01-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='panel',
        ),
    ]
