# Generated by Django 4.1.5 on 2023-01-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_panel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='panel',
        ),
    ]
