# Generated by Django 4.1.5 on 2023-01-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_age_remove_customuser_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cal',
            field=models.PositiveIntegerField(help_text='Kcal', null=True, verbose_name='Target calories'),
        ),
    ]
