# Generated by Django 4.1.5 on 2023-01-13 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_panel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Date'),
        ),
    ]
